site_name: Vesperia Guide
nav:
  - Home: index.md
  - Missables Checklist: missables.md
  - Spoiler-free Missables Checklist: missables_spoiler_free.md
  - Recipes Checklist: recipes.md
  - CHANGELOG: CHANGELOG.md
markdown_extensions:
  - markdown_checklists.extension
  - pymdownx.tilde
extra_css:
  - css/custom.css
extra_javascript:
  - js/checkbox.js
theme:
  name: rtd-dropdown
  custom_dir: custom_theme/
